const data = {
  courses: [
    {
      name: "English 1 for Credit Recovery", //absolute
      code: "1001001", //absolute
      type: "English", //absolute
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400, //absolute
      seats: 1000, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
    {
      name: "English 2 for Credit Recovery",
      code: "1001002",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 400, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
    {
      name: "English 3 for Credit Recovery",
      code: "1001003",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 3,
      cost: 400,
      seats: 100, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
    {
      name: "English 4 for Credit Recovery",
      code: "1001004",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 30, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
    {
      name: "English 5 for Credit Recovery",
      code: "1001005",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 3,
      cost: 400,
      seats: 10, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
    {
      name: "English 6 for Credit Recovery",
      code: "1001006",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 10,
      rating: 2,
      cost: 400,
      seats: 0, 
      desription: "English 1 for Credit Recovery",
      career: "No",
      prequisites: "",
      requirement: "",
      endOfCourse: "",
    },
  ],
};
export default data;
