import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Sanskar",
      email: "sanskar841singh@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Admin",
      email: "Admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
  ],
  courses: [
    {
      name: "English 1 for Credit Recovery", //absolute
      code: "1001001", //absolute
      type: "English 1", //absolute
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 1",
      level: "Regular",
      weight: 3.5,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400, //absolute
      seats: 1000,
      description: "English 1 for Credit Recovery description",
      career: "No",
      prequisites: "November",
      requirement: "Graduation",
      endOfCourse: "March",
    },
    {
      name: "English 2 for Credit Recovery",
      code: "1001002",
      type: "English 2",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 2",
      level: "Regular",
      weight: 4.5,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 400,
      description: "English 2 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "November",
    },
    {
      name: "English 3 for Credit Recovery",
      code: "1001003",
      type: "English 3",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 3",
      level: "Regular",
      weight: 3.0,
      subcategory: "English",
      review: 10,
      rating: 3,
      cost: 400,
      seats: 100,
      description: "English 3 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "August",
    },
    {
      name: "English 4 for Credit Recovery",
      code: "1001004",
      type: "English 4",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 4",
      level: "Regular",
      weight: 5.0,
      subcategory: "English",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 30,
      description: "English 4 for Credit Recovery description",
      career: "No",
      prequisites: "February",
      requirement: "Semi Graduation",
      endOfCourse: "December",
    },
    {
      name: "English 5 for Credit Recovery",
      code: "1001005",
      type: "English 5",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 5",
      level: "Regular",
      weight: 2.0,
      subcategory: "English",
      review: 88,
      rating: 3,
      cost: 9000,
      seats: 100,
      description: "English 5 for Credit Recovery description",
      career: "No",
      prequisites: "March",
      requirement: "Graduation",
      endOfCourse: "September",
    },
    {
      name: "English 6 for Credit Recovery",
      code: "1001006",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 6",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 100,
      rating: 2,
      cost: 3000,
      seats: 0,
      description: "English 6 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "October",
    },
    {
      name: "English 7 for Credit Recovery",
      code: "1001007",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 7",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 0,
      rating: 2,
      cost: 1000,
      seats: 0,
      description: "English 7 for Credit Recovery description",
      career: "Yes",
      prequisites: "May",
      requirement: "None",
      endOfCourse: "November",
    },
    {
      name: "English 8 for Credit Recovery",
      code: "1001008",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 8",
      level: "Regular",
      weight: 4.0,
      subcategory: "English",
      review: 15,
      rating: 1,
      cost: 1200,
      seats: 0,
      description: "English 8 for Credit Recovery description",
      career: "Yes",
      prequisites: "June",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "English 9 for Credit Recovery",
      code: "1001009",
      type: "English",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "English 9",
      level: "Regular",
      weight: 2.5,
      subcategory: "English",
      review: 35,
      rating: 4,
      cost: 2000,
      seats: 0,
      description: "English 9 for Credit Recovery description",
      career: "Yes",
      prequisites: "Marh",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "English 10 for Credit Recovery",
      code: "1001010",
      type: "English",
      tag: "Tagline",
      credits: 4.0,
      length: "Credit Recovery",
      category: "English 10",
      level: "Regular",
      weight: 3.5,
      subcategory: "English",
      review: 105,
      rating: 4,
      cost: 2500,
      seats: 100,
      description: "English 10 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "December",
    },
    {
      name: "Mathematics 1 for Credit Recovery", //absolute
      code: "1001011", //absolute
      type: "Mathematics 1", //absolute
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 1",
      level: "Regular",
      weight: 3.5,
      subcategory: "Mathematics",
      review: 10,
      rating: 4,
      cost: 400, //absolute
      seats: 1000,
      description: "Mathematics 1 for Credit Recovery description",
      career: "No",
      prequisites: "November",
      requirement: "Graduation",
      endOfCourse: "March",
    },
    {
      name: "Mathematics 2 for Credit Recovery",
      code: "1001012",
      type: "Mathematics 2",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 2",
      level: "Regular",
      weight: 4.5,
      subcategory: "Mathematics",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 400,
      description: "Mathematics 2 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "November",
    },
    {
      name: "Mathematics 3 for Credit Recovery",
      code: "1001013",
      type: "Mathematics 3",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 3",
      level: "Regular",
      weight: 3.0,
      subcategory: "Mathematics",
      review: 10,
      rating: 3,
      cost: 400,
      seats: 100,
      description: "Mathematics 3 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "August",
    },
    {
      name: "Mathematics 4 for Credit Recovery",
      code: "1001014",
      type: "Mathematics 4",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 4",
      level: "Regular",
      weight: 5.0,
      subcategory: "Mathematics",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 30,
      description: "Mathematics 4 for Credit Recovery description",
      career: "No",
      prequisites: "February",
      requirement: "Semi Graduation",
      endOfCourse: "December",
    },
    {
      name: "Mathematics 5 for Credit Recovery",
      code: "1001015",
      type: "Mathematics 5",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 5",
      level: "Regular",
      weight: 2.0,
      subcategory: "Mathematics",
      review: 88,
      rating: 3,
      cost: 9000,
      seats: 100,
      description: "Mathematics 5 for Credit Recovery description",
      career: "No",
      prequisites: "March",
      requirement: "Graduation",
      endOfCourse: "September",
    },
    {
      name: "Mathematics 6 for Credit Recovery",
      code: "1001016",
      type: "Mathematics",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 6",
      level: "Regular",
      weight: 4.0,
      subcategory: "Mathematics",
      review: 100,
      rating: 2,
      cost: 3000,
      seats: 0,
      description: "Mathematics 6 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "October",
    },
    {
      name: "Mathematics 7 for Credit Recovery",
      code: "1001017",
      type: "Mathematics",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 7",
      level: "Regular",
      weight: 4.0,
      subcategory: "Mathematics",
      review: 0,
      rating: 2,
      cost: 1000,
      seats: 0,
      description: "Mathematics 7 for Credit Recovery description",
      career: "Yes",
      prequisites: "May",
      requirement: "None",
      endOfCourse: "November",
    },
    {
      name: "Mathematics 8 for Credit Recovery",
      code: "1001018",
      type: "Mathematics",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 8",
      level: "Regular",
      weight: 4.0,
      subcategory: "Mathematics",
      review: 15,
      rating: 1,
      cost: 1200,
      seats: 0,
      description: "Mathematics 8 for Credit Recovery description",
      career: "Yes",
      prequisites: "June",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "Mathematics 9 for Credit Recovery",
      code: "1001019",
      type: "Mathematics",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "Mathematics 9",
      level: "Regular",
      weight: 2.5,
      subcategory: "Mathematics",
      review: 35,
      rating: 4,
      cost: 2000,
      seats: 0,
      description: "Mathematics 9 for Credit Recovery description",
      career: "Yes",
      prequisites: "Marh",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "Mathematics 10 for Credit Recovery",
      code: "1001020",
      type: "Mathematics",
      tag: "Tagline",
      credits: 4.0,
      length: "Credit Recovery",
      category: "Mathematics 10",
      level: "Regular",
      weight: 3.5,
      subcategory: "Mathematics",
      review: 105,
      rating: 4,
      cost: 2500,
      seats: 100,
      description: "Mathematics 10 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "December",
    },
    {
      name: "French 1 for Credit Recovery", //absolute
      code: "1001021", //absolute
      type: "French 1", //absolute
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 1",
      level: "Regular",
      weight: 3.5,
      subcategory: "French",
      review: 10,
      rating: 4,
      cost: 400, //absolute
      seats: 1000,
      description: "French 1 for Credit Recovery description",
      career: "No",
      prequisites: "November",
      requirement: "Graduation",
      endOfCourse: "March",
    },
    {
      name: "French 2 for Credit Recovery",
      code: "1001022",
      type: "French 2",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 2",
      level: "Regular",
      weight: 4.5,
      subcategory: "French",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 400,
      description: "French 2 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "November",
    },
    {
      name: "French 3 for Credit Recovery",
      code: "1001023",
      type: "French 3",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 3",
      level: "Regular",
      weight: 3.0,
      subcategory: "French",
      review: 10,
      rating: 3,
      cost: 400,
      seats: 100,
      description: "French 3 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "August",
    },
    {
      name: "French 4 for Credit Recovery",
      code: "1001024",
      type: "French 4",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 4",
      level: "Regular",
      weight: 5.0,
      subcategory: "French",
      review: 10,
      rating: 4,
      cost: 400,
      seats: 30,
      description: "French 4 for Credit Recovery description",
      career: "No",
      prequisites: "February",
      requirement: "Semi Graduation",
      endOfCourse: "December",
    },
    {
      name: "French 5 for Credit Recovery",
      code: "1001025",
      type: "French 5",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 5",
      level: "Regular",
      weight: 2.0,
      subcategory: "French",
      review: 88,
      rating: 3,
      cost: 9000,
      seats: 100,
      description: "French 5 for Credit Recovery description",
      career: "No",
      prequisites: "March",
      requirement: "Graduation",
      endOfCourse: "September",
    },
    {
      name: "French 6 for Credit Recovery",
      code: "1001026",
      type: "French",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 6",
      level: "Regular",
      weight: 4.0,
      subcategory: "French",
      review: 100,
      rating: 2,
      cost: 3000,
      seats: 0,
      description: "French 6 for Credit Recovery description",
      career: "No",
      prequisites: "April",
      requirement: "Semi Graduation",
      endOfCourse: "October",
    },
    {
      name: "French 7 for Credit Recovery",
      code: "1001027",
      type: "French",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 7",
      level: "Regular",
      weight: 4.0,
      subcategory: "French",
      review: 0,
      rating: 2,
      cost: 1000,
      seats: 0,
      description: "French 7 for Credit Recovery description",
      career: "Yes",
      prequisites: "May",
      requirement: "None",
      endOfCourse: "November",
    },
    {
      name: "French 8 for Credit Recovery",
      code: "1001028",
      type: "French",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 8",
      level: "Regular",
      weight: 4.0,
      subcategory: "French",
      review: 15,
      rating: 1,
      cost: 1200,
      seats: 0,
      description: "French 8 for Credit Recovery description",
      career: "Yes",
      prequisites: "June",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "French 9 for Credit Recovery",
      code: "1001029",
      type: "French",
      tag: "Tagline",
      credits: 1.0,
      length: "Credit Recovery",
      category: "French 9",
      level: "Regular",
      weight: 2.5,
      subcategory: "French",
      review: 35,
      rating: 4,
      cost: 2000,
      seats: 0,
      description: "French 9 for Credit Recovery description",
      career: "Yes",
      prequisites: "Marh",
      requirement: "None",
      endOfCourse: "December",
    },
    {
      name: "French 10 for Credit Recovery",
      code: "1001030",
      type: "French",
      tag: "Tagline",
      credits: 4.0,
      length: "Credit Recovery",
      category: "French 10",
      level: "Regular",
      weight: 3.5,
      subcategory: "French",
      review: 105,
      rating: 4,
      cost: 2500,
      seats: 100,
      description: "French 10 for Credit Recovery description",
      career: "No",
      prequisites: "January",
      requirement: "Graduation",
      endOfCourse: "December",
    }
  ],
};
export default data;
